# Generated by Django 5.0.6 on 2024-05-31 10:20

import django.db.models.deletion
import photomanager.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashpath', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=15, null=True)),
                ('bust_size', models.CharField(blank=True, max_length=10, null=True)),
                ('measurements', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashpath', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to=photomanager.models.image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('hashpath', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photomanager.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='photomanager.profile'),
        ),
    ]
