services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=imgupp
      - DB_USER=imgupp
      - DB_PASSWORD=imgupp
      - DB_HOST=postgres
      - DB_PORT=5432
      - MONGO_DB_NAME=imgupp
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/imgupp_root
      - ./media:/imgupp_root/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: imgupp
      POSTGRES_USER: imgupp
      POSTGRES_PASSWORD: imgupp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: